# Generated by Django 5.1.4 on 2024-12-19 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Dataset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("file", models.FileField(upload_to="datasets/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "dataset_table",
            },
        ),
        migrations.CreateModel(
            name="Densenet_model",
            fields=[
                ("S_No", models.AutoField(primary_key=True, serialize=False)),
                ("model_accuracy", models.CharField(default="93.8", max_length=10)),
            ],
            options={
                "db_table": "Densenet_model",
            },
        ),
        migrations.CreateModel(
            name="MobileNet_model",
            fields=[
                ("S_No", models.AutoField(primary_key=True, serialize=False)),
                ("model_accuracy", models.CharField(default="97.7", max_length=10)),
            ],
            options={
                "db_table": "MobileNet_model",
            },
        ),
    ]
