# Generated by Django 5.1.7 on 2025-05-14 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobilenet_model',
            name='model_accuracy',
            field=models.CharField(default='70.7', max_length=10),
        ),
    ]
